version: '3.7'
services:
  mysql:
    image: mysql:8.0.36
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - DB_URL=jdbc:mysql://localhost:3306/app
      - DB_USER=app
      - DB_PASS=pass